services:
  twitch-drops-miner:
    build: .
    container_name: twitch-drops-miner
    ports:
      - "5800:5800"
    volumes:
      - ./config:/TwitchDropsMiner/config
      - ./cache:/TwitchDropsMiner/cache
    environment:
      - DARK_MODE=1
    restart: unless-stopped
