services:
  twitch-drops-miner:
    build: .
    container_name: twitch-drops-miner
    restart: on-failure
    pull_policy: always
    ports:
      - "5800:5800"
    environment:
      - DARK_MODE=1
      - USER_ID=568
      - GROUP_ID=568
    volumes:
      - ./config:/config
      - cache:/cache
volumes:
  cache:
